// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as osapi$0 from "./osapi/models.js";

/**
 * @returns {$CancellablePromise<osapi$0.Window[]>}
 */
export function GetAllActiveWindows() {
    return $Call.ByID(1870892949).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_: `${number}`]: string }>}
 */
export function GetAllHotkeys() {
    return $Call.ByID(2845810777).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} handle
 * @returns {$CancellablePromise<void>}
 */
export function SetBorderlessFullscreen(handle) {
    return $Call.ByID(2770650965, handle);
}

/**
 * @param {number} handle
 * @param {string} hotkey
 * @returns {$CancellablePromise<void>}
 */
export function SetHotkey(handle, hotkey) {
    return $Call.ByID(2969235429, handle, hotkey);
}

/**
 * @param {number} handle
 * @returns {$CancellablePromise<void>}
 */
export function SetWindowed(handle) {
    return $Call.ByID(3190592750, handle);
}

// Private type creation functions
const $$createType0 = osapi$0.Window.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
