// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as osapi$0 from "../github.com/Bensterriblescripts/Lib-Handlers/osapi/models.js";

/**
 * @returns {$CancellablePromise<osapi$0.Window[]>}
 */
export function GetAllActiveWindows() {
    return $Call.ByID(64613779).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: string[] }>}
 */
export function GetAllHotkeys() {
    return $Call.ByID(2782383863).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} handle
 * @returns {$CancellablePromise<void>}
 */
export function SetBorderlessFullscreen(handle) {
    return $Call.ByID(1005271035, handle);
}

/**
 * @param {number} handle
 * @returns {$CancellablePromise<void>}
 */
export function SetFocus(handle) {
    return $Call.ByID(2616498367, handle);
}

/**
 * @param {string} executable
 * @param {string} kotkeymod
 * @param {string} hotkey
 * @returns {$CancellablePromise<void>}
 */
export function SetHotkey(executable, kotkeymod, hotkey) {
    return $Call.ByID(3240562487, executable, kotkeymod, hotkey);
}

/**
 * @param {number} handle
 * @returns {$CancellablePromise<void>}
 */
export function SetWindowed(handle) {
    return $Call.ByID(2197968152, handle);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ToggleHotkeys() {
    return $Call.ByID(400143178);
}

// Private type creation functions
const $$createType0 = osapi$0.Window.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
