// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as osapi$0 from "../github.com/Bensterriblescripts/Lib-Handlers/osapi/models.js";

/**
 * @returns {$CancellablePromise<osapi$0.Window[]>}
 */
export function GetAllActiveWindows() {
    return $Call.ByID(2408806900).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} handle
 * @returns {$CancellablePromise<void>}
 */
export function SetBorderlessFullscreen(handle) {
    return $Call.ByID(1654841156, handle);
}

/**
 * @param {number} handle
 * @returns {$CancellablePromise<void>}
 */
export function SetWindowed(handle) {
    return $Call.ByID(127463687, handle);
}

// Private type creation functions
const $$createType0 = osapi$0.Window.createFrom;
const $$createType1 = $Create.Array($$createType0);
