// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Window {
    /**
     * Creates a new Window instance.
     * @param {Partial<Window>} [$$source = {}] - The source object to create the Window.
     */
    constructor($$source = {}) {
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("FullTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["FullTitle"] = "";
        }
        if (!("Handle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Handle"] = 0;
        }
        if (!("Process" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Process"] = 0;
        }
        if (!("Executable" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Executable"] = "";
        }
        if (!("Style" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Style"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Window instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Window}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Window(/** @type {Partial<Window>} */($$parsedSource));
    }
}
