// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RECT {
    /**
     * Creates a new RECT instance.
     * @param {Partial<RECT>} [$$source = {}] - The source object to create the RECT.
     */
    constructor($$source = {}) {
        if (!("Left" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Left"] = 0;
        }
        if (!("Top" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Top"] = 0;
        }
        if (!("Right" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Right"] = 0;
        }
        if (!("Bottom" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Bottom"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RECT instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RECT}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RECT(/** @type {Partial<RECT>} */($$parsedSource));
    }
}

export class Window {
    /**
     * Creates a new Window instance.
     * @param {Partial<Window>} [$$source = {}] - The source object to create the Window.
     */
    constructor($$source = {}) {
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("FullTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["FullTitle"] = "";
        }
        if (!("Handle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Handle"] = 0;
        }
        if (!("Process" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Process"] = 0;
        }
        if (!("Executable" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Executable"] = "";
        }
        if (!("WindowState" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["WindowState"] = "";
        }
        if (!("OriginalRect" in $$source)) {
            /**
             * @member
             * @type {RECT}
             */
            this["OriginalRect"] = (new RECT());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Window instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Window}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("OriginalRect" in $$parsedSource) {
            $$parsedSource["OriginalRect"] = $$createField6_0($$parsedSource["OriginalRect"]);
        }
        return new Window(/** @type {Partial<Window>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = RECT.createFrom;
